version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram-aiogram-bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CHATGPT_API_KEY=${CHATGPT_API_KEY}
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
